<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>


<nav class="navigation navbar navbar-default" data-action="navigation">
    <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
        <ul class="nav navbar-nav"  data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?= /* @escapeNotVerified */ $_menu ?>
            <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
        </ul>
    </div>
</nav>

 


